crontab wasnt working

diff --git a/templates/default/cut_tiles.sh.erb b/templates/default/cut_tiles.sh.erb
--- a/templates/default/cut_tiles.sh.erb
+++ b/templates/default/cut_tiles.sh.erb
@@ -13,13 +13,11 @@ trap 'rm $LOCK_FILE' EXIT 1 2 3 6
 # if they want updates then we need to install crontabs
 if [ "<%= node[:valhalla][:with_updates] %>" == "yes" ]; then
   # remove cron jobs.
-  crontab -r || true
+  crontab -r 2>/dev/null || true
 
-  # add new cron job for updates.
-  (crontab -l 2>/dev/null; echo "*/5 * * * * cd <%= node[:valhalla][:base_dir] %>; <%= node[:valhalla][:conf_dir] %>/update_tiles.sh >> <%= node[:valhalla][:log_dir] %>/update.log 2>&1") | crontab -
-
-  # add new cron job for log clean up.
-  (crontab -l 2>/dev/null; echo "0 0 * * 0 rm <%= node[:valhalla][:log_dir] %>/*.log") | crontab -
+  # updates and log cleanup
+  (echo "*/5 * * * * cd <%= node[:valhalla][:base_dir] %>; <%= node[:valhalla][:conf_dir] %>/update_tiles.sh >> <%= node[:valhalla][:log_dir] %>/update.log 2>&1";
+   echo "0 0 * * 0 rm <%= node[:valhalla][:log_dir] %>/*.log") | crontab -
 # they just want us to cut tiles once
 else
   <%= node[:valhalla][:conf_dir] %>/update_tiles.sh >> <%= node[:valhalla][:log_dir] %>/update.log 2>&1
